#!/usr/bin/env python

import sys
import os
import errno
import requests
from requests.auth import HTTPBasicAuth
from clint.textui import progress
import click

altius = 'resources.altius.org'
username = 'encode'
password = 'collabor8'

hg_e_map = { 'E017' : 'IMR90 fetal lung fibroblasts',
             'E002' : 'ES-WA7',
             'E008' : 'H9',
             'E001' : 'ES-I3',
             'E015' : 'HUES6',
             'E014' : 'HUES48',
             'E016' : 'HUES64',
             'E003' : 'H1',
             'E024' : 'ES-UCSF4',
             'E020' : 'iPS-20b',
             'E019' : 'iPS-18',
             'E018' : 'iPS-15b',
             'E021' : 'iPS DF 6.9',
             'E022' : 'iPS DF 19.11',
             'E007' : 'H1 Derived Neuronal Progenitor Cultured', 
             'E009' : 'H9 Derived Neuronal Progenitor Cultured',
             'E010' : 'H9 Derived Neuron Cultured',
             'E013' : 'hESC Derived CD56+ Mesoderm Cultured',
             'E012' : 'hESC Derived CD56+ Ectoderm Cultured', 
             'E011' : 'hESC Derived CD184+ Endoderm Cultured',
             'E004' : 'H1 BMP4 Derived Mesendoderm Cultured',
             'E005' : 'H1 BMP4 Derived Trophoblast Cultured',
             'E006' : 'H1 Derived Mesenchymal Stem Cells',
             'E062' : 'Primary mononuclear cells from peripheral blood',
             'E034' : 'Primary T cells from peripheral blood',
             'E045' : 'Primary T cells effector/memory enriched from peripheral blood',
             'E033' : 'Primary T cells from cord blood',
             'E044' : 'Primary T regulatory cells from peripheral blood',
             'E043' : 'Primary T helper cells from peripheral blood',
             'E039' : 'Primary T helper naive cells from peripheral blood',
             'E041' : 'Primary T helper cells PMA-I stimulated',
             'E042' : 'Primary T helper 17 cells PMA-I stimulated',
             'E040' : 'Primary T helper memory cells from peripheral blood 1',
             'E037' : 'Primary T helper memory cells from peripheral blood 2',
             'E048' : 'Primary T CD8+ memory cells from peripheral blood',
             'E038' : 'Primary T helper naive cells from peripheral blood',
             'E047' : 'Primary T CD8+ naive cells from peripheral blood',
             'E029' : 'Primary monocytes from peripheral blood',
             'E031' : 'Primary B cells from cord blood',
             'E035' : 'Primary hematopoietic stem cells',
             'E051' : 'Primary hematopoietic stem cells G-CSF-mobilized Male',
             'E050' : 'Primary hematopoietic stem cells G-CSF-mobilized Female',
             'E036' : 'Primary hematopoietic stem cells short term culture',
             'E032' : 'Primary B cells from peripheral blood',
             'E046' : 'Primary Natural Killer cells from peripheral blood',
             'E030' : 'Primary neutrophils from peripheral blood',
             'E026' : 'Bone Marrow Derived Cultured Mesenchymal Stem Cells',
             'E049' : 'Mesenchymal Stem Cell Derived Chondrocyte Cultured',
             'E025' : 'Adipose Derived Mesenchymal Stem Cell Cultured',
             'E023' : 'Mesenchymal Stem Cell Derived Adipocyte Cultured',
             'E052' : 'Muscle Satellite Cultured',
             'E055' : 'Foreskin Fibroblast Primary Cells skin01',
             'E056' : 'Foreskin Fibroblast Primary Cells skin02', 
             'E059' : 'Foreskin Melanocyte Primary Cells skin01',
             'E061' : 'Foreskin Melanocyte Primary Cells skin03',
             'E057' : 'Foreskin Keratinocyte Primary Cells skin02',
             'E058' : 'Foreskin Keratinocyte Primary Cells skin03',
             'E028' : 'Breast variant Human Mammary Epithelial Cells (vHMEC)',
             'E027' : 'Breast Myoepithelial Primary Cells',
             'E054' : 'Ganglion Eminence derived primary cultured neurospheres',
             'E053' : 'Cortex derived primary cultured neurospheres',
             'E112' : 'Thymus',
             'E093' : 'Fetal Thymus',
             'E071' : 'Brain Hippocampus Middle',
             'E074' : 'Brain Substantia Nigra',
             'E068' : 'Brain Anterior Caudate',
             'E069' : 'Brain Cingulate Gyrus',
             'E072' : 'Brain Inferior Temporal Lobe',
             'E067' : 'Brain Angular Gyrus',
             'E073' : 'Brain_Dorsolateral_Prefrontal_Cortex',
             'E070' : 'Brain Germinal Matrix',
             'E082' : 'Fetal Brain Female',
             'E081' : 'Fetal Brain Male',
             'E063' : 'Adipose Nuclei',
             'E100' : 'Psoas Muscle',
             'E108' : 'Skeletal Muscle Female',
             'E107' : 'Skeletal Muscle Male',
             'E089' : 'Fetal Muscle Trunk',
             'E090' : 'Fetal Muscle Leg',
             'E083' : 'Fetal Heart',
             'E104' : 'Right Atrium',
             'E095' : 'Left Ventricle',
             'E105' : 'Right Ventricle',
             'E065' : 'Aorta',
             'E078' : 'Duodenum Smooth Muscle',
             'E076' : 'Colon Smooth Muscle',
             'E103' : 'Rectal Smooth Muscle',
             'E111' : 'Stomach Smooth Muscle',
             'E092' : 'Fetal Stomach',
             'E085' : 'Fetal Intestine Small',
             'E084' : 'Fetal Intestine Large',
             'E109' : 'Small Intestine',
             'E106' : 'Sigmoid Colon',
             'E075' : 'Colonic Mucosa',
             'E101' : 'Rectal Mucosa Donor 29',
             'E102' : 'Rectal Mucosa Donor 31',
             'E110' : 'Stomach Mucosa',
             'E077' : 'Duodenum Mucosa',
             'E079' : 'Esophagus',
             'E094' : 'Gastric',
             'E099' : 'Placenta Amnion',
             'E086' : 'Fetal Kidney',
             'E088' : 'Fetal Lung',
             'E097' : 'Ovary',
             'E087' : 'Pancreatic Islets',
             'E080' : 'Fetal Adrenal Gland',
             'E091' : 'Placenta',
             'E066' : 'Liver',
             'E098' : 'Pancreas',
             'E096' : 'Lung',
             'E113' : 'Spleen',
             'E114' : 'A549 EtOH 0.02pct Lung Carcinoma',
             'E115' : 'Dnd41 TCell Leukemia',
             'E116' : 'GM12878 Lymphoblastoid',
             'E117' : 'HeLa-S3 Cervical Carcinoma',
             'E118' : 'HepG2 Hepatocellular Carcinoma',
             'E119' : 'HMEC Mammary Epithelial Primary Cells',
             'E120' : 'HSMM Skeletal Muscle Myoblasts',
             'E121' : 'HSMM cell derived Skeletal Muscle Myotubes',
             'E122' : 'HUVEC Umbilical Vein Endothelial Primary Cells',
             'E123' : 'K562 Leukemia',
             'E124' : 'Monocytes-CD14+ RO01746 Primary Cells',
             'E125' : 'NH-A Astrocytes Primary Cells',
             'E126' : 'NHDF-Ad Adult Dermal Fibroblast Primary Cells',
             'E127' : 'NHEK-Epidermal Keratinocyte Primary Cells',
             'E128' : 'NHLF Lung Fibroblast Primary Cells',
             'E129' : 'Osteoblast Primary Cells' }

hg_e_prefixes = { 'Adipose' : [ 'E063' ],
                  'adult_blood_reference' : [ 'E004',
                                              'E005',
                                              'E006',
                                              'E007',
                                              'E009',
                                              'E010',
                                              'E011',
                                              'E012',
                                              'E013',
                                              'E018',
                                              'E019',
                                              'E020',
                                              'E021',
                                              'E022',
                                              'E023',
                                              'E025',
                                              'E026',
                                              'E027',
                                              'E028',
                                              'E049',
                                              'E052',
                                              'E053',
                                              'E054',
                                              'E055',
                                              'E056',
                                              'E057',
                                              'E058',
                                              'E059',
                                              'E061',
                                              'E063',
                                              'E065',
                                              'E066',
                                              'E067',
                                              'E068',
                                              'E069',
                                              'E070',
                                              'E071',
                                              'E072',
                                              'E073',
                                              'E074',
                                              'E075',
                                              'E076',
                                              'E077',
                                              'E078',
                                              'E079',
                                              'E087',
                                              'E094',
                                              'E095',
                                              'E096',
                                              'E097',
                                              'E098',
                                              'E100',
                                              'E101',
                                              'E102',
                                              'E103',
                                              'E104',
                                              'E105',
                                              'E106',
                                              'E107',
                                              'E108',
                                              'E109',
                                              'E110',
                                              'E111',
                                              'E112',
                                              'E113',
                                              'E119',
                                              'E120',
                                              'E121',
                                              'E125',
                                              'E126',
                                              'E127',
                                              'E128',
                                              'E129' ],
                  'adult_blood_sample' : [ 'E029',
                                           'E030',
                                           'E032',
                                           'E034',
                                           'E035',
                                           'E036',
                                           'E037',
                                           'E038',
                                           'E039',
                                           'E040',
                                           'E041',
                                           'E042',
                                           'E043',
                                           'E044',
                                           'E045',
                                           'E046',
                                           'E047',
                                           'E048',
                                           'E050',
                                           'E051',
                                           'E062',
                                           'E116',
                                           'E124' ],
                  'Blood_T-cell' : [ 'E033',
                                     'E034',
                                     'E037',
                                     'E038',
                                     'E039',
                                     'E040',
                                     'E041',
                                     'E042',
                                     'E043',
                                     'E044',
                                     'E045',
                                     'E047',
                                     'E048',
                                     'E062' ],
                  'Non-T-cell_Roadmap' : [ 'E001',
                                           'E002',
                                           'E003',
                                           'E004',
                                           'E005',
                                           'E006',
                                           'E007',
                                           'E008',
                                           'E009',
                                           'E010',
                                           'E011',
                                           'E012',
                                           'E013',
                                           'E014',
                                           'E015',
                                           'E016',
                                           'E017',
                                           'E018',
                                           'E019',
                                           'E020',
                                           'E021',
                                           'E022',
                                           'E023',
                                           'E024',
                                           'E025',
                                           'E026',
                                           'E027',
                                           'E028',
                                           'E029',
                                           'E030',
                                           'E031',
                                           'E032',
                                           'E035',
                                           'E036',
                                           'E046',
                                           'E049',
                                           'E050',
                                           'E051',
                                           'E052',
                                           'E053',
                                           'E054',
                                           'E055',
                                           'E056',
                                           'E057',
                                           'E058',
                                           'E059',
                                           'E061',
                                           'E063',
                                           'E065',
                                           'E066',
                                           'E067',
                                           'E068',
                                           'E069',
                                           'E070',
                                           'E071',
                                           'E072',
                                           'E073',
                                           'E074',
                                           'E075',
                                           'E076',
                                           'E077',
                                           'E078',
                                           'E079',
                                           'E080',
                                           'E081',
                                           'E082',
                                           'E083',
                                           'E084',
                                           'E085',
                                           'E086',
                                           'E087',
                                           'E088',
                                           'E089',
                                           'E090',
                                           'E091',
                                           'E092',
                                           'E093',
                                           'E094',
                                           'E095',
                                           'E096',
                                           'E097',
                                           'E098',
                                           'E099',
                                           'E100',
                                           'E101',
                                           'E102',
                                           'E103',
                                           'E104',
                                           'E105',
                                           'E106',
                                           'E107',
                                           'E108',
                                           'E109',
                                           'E110',
                                           'E111',
                                           'E112',
                                           'E113',
                                           'E114',
                                           'E115',
                                           'E116',
                                           'E117',
                                           'E118',
                                           'E119',
                                           'E120',
                                           'E121',
                                           'E122',
                                           'E123',
                                           'E124',
                                           'E125',
                                           'E126',
                                           'E127',
                                           'E128',
                                           'E129' ],
                  'Brain' : [ 'E067',
                              'E068',
                              'E069',
                              'E070',
                              'E071',
                              'E072',
                              'E073',
                              'E074',
                              'E081',
                              'E082' ],
                  'CellLine' : [ 'E017',
                                 'E114',
                                 'E115',
                                 'E117',
                                 'E118' ],
                  'cord_blood_reference' : [ 'E001',
                                             'E002',
                                             'E003',
                                             'E004',
                                             'E005',
                                             'E006',
                                             'E007',
                                             'E008',
                                             'E009',
                                             'E010',
                                             'E011',
                                             'E012',
                                             'E013',
                                             'E014',
                                             'E015',
                                             'E016',
                                             'E017',
                                             'E018',
                                             'E019',
                                             'E020',
                                             'E021',
                                             'E022',
                                             'E023',
                                             'E024',
                                             'E025',
                                             'E026',
                                             'E027',
                                             'E028',
                                             'E049',
                                             'E052',
                                             'E053',
                                             'E054',
                                             'E055',
                                             'E056',
                                             'E057',
                                             'E058',
                                             'E059',
                                             'E061',
                                             'E063',
                                             'E065',
                                             'E066',
                                             'E067',
                                             'E068',
                                             'E069',
                                             'E070',
                                             'E071',
                                             'E072',
                                             'E073',
                                             'E074',
                                             'E075',
                                             'E076',
                                             'E077',
                                             'E078',
                                             'E079',
                                             'E080',
                                             'E081',
                                             'E082',
                                             'E083',
                                             'E084',
                                             'E085',
                                             'E086',
                                             'E087',
                                             'E088',
                                             'E089',
                                             'E090',
                                             'E091',
                                             'E092',
                                             'E093',
                                             'E094',
                                             'E095',
                                             'E096',
                                             'E097',
                                             'E098',
                                             'E099',
                                             'E100',
                                             'E101',
                                             'E102',
                                             'E103',
                                             'E104',
                                             'E105',
                                             'E106',
                                             'E107',
                                             'E108',
                                             'E109',
                                             'E110',
                                             'E111',
                                             'E112',
                                             'E113',
                                             'E119',
                                             'E120',
                                             'E121',
                                             'E122',
                                             'E125',
                                             'E126',
                                             'E127',
                                             'E128',
                                             'E129' ],
                  'cord_blood_sample' : [ 'E029',
                                          'E030',
                                          'E031',
                                          'E032',
                                          'E033',
                                          'E034',
                                          'E035',
                                          'E036',
                                          'E037',
                                          'E038',
                                          'E039',
                                          'E040',
                                          'E041',
                                          'E042',
                                          'E043',
                                          'E044',
                                          'E045',
                                          'E046',
                                          'E047',
                                          'E048',
                                          'E050',
                                          'E051',
                                          'E062',
                                          'E116',
                                          'E124' ],
                  'Digestive' : [ 'E075',
                                  'E077',
                                  'E079',
                                  'E084',
                                  'E085',
                                  'E092',
                                  'E094',
                                  'E101',
                                  'E102',
                                  'E106',
                                  'E109',
                                  'E110' ],
               'ENCODE2012' : [ 'E114',
                                'E115',
                                'E116',
                                'E117',
                                'E118',
                                'E119', 
                                'E120', 
                                'E121',
                                'E122',
                                'E123',
                                'E124',
                                'E125',
                                'E126',
                                'E127',
                                'E128',
                                'E129' ],
               'Epithelial' : [ 'E027',
                                'E028',
                                'E055',
                                'E056',
                                'E057',
                                'E058',
                                'E059',
                                'E061' ],
               'ES-deriv' : [ 'E004',
                              'E005',
                              'E006',
                              'E007',
                              'E009',
                              'E010',
                              'E011',
                              'E012',
                              'E013' ],
               'ESC' : [ 'E001',
                         'E002',
                         'E003',
                         'E008',
                         'E014',
                         'E015',
                         'E016',
                         'E024' ],
               'Female' : [ 'E001',
                            'E002',
                            'E008',
                            'E009', 
                            'E010',
                            'E014',
                            'E015',
                            'E017',
                            'E018',
                            'E019',
                            'E023',
                            'E024',
                            'E025',
                            'E027',
                            'E028',
                            'E053',
                            'E054',
                            'E063',
                            'E075',
                            'E076',
                            'E082',
                            'E089',
                            'E090',
                            'E091',
                            'E092',
                            'E093',
                            'E096',
                            'E097',
                            'E101',
                            'E102',
                            'E103',
                            'E108',
                            'E111',
                            'E116',
                            'E117',
                            'E123',
                            'E124',
                            'E126' ],
               'Heart' : [ 'E065',
                           'E083',
                           'E095',
                           'E104',
                           'E105' ],
               'HSC_B-cell' : [ 'E029',
                                'E030',
                                'E031',
                                'E032',
                                'E035',
                                'E036',
                                'E046',
                                'E050',
                                'E051' ],
               'IMR90' : [ 'E017' ],
               'iPSC' : [ 'E018', 
                          'E019',
                          'E020',
                          'E021',
                          'E022' ],
               'Male' : [ 'E003',
                          'E004',
                          'E005',
                          'E006',
                          'E007',
                          'E011',
                          'E012',
                          'E013',
                          'E016',
                          'E020',
                          'E021',
                          'E022',
                          'E029',
                          'E030',
                          'E032',
                          'E034',
                          'E046',
                          'E051',
                          'E055',
                          'E056',
                          'E057',
                          'E058',
                          'E059',
                          'E061',
                          'E062',
                          'E065',
                          'E070',
                          'E071',
                          'E077',
                          'E078',
                          'E079',
                          'E080',
                          'E084',
                          'E085',
                          'E087',
                          'E094',
                          'E095',
                          'E098',
                          'E099',
                          'E100',
                          'E104',
                          'E105',
                          'E106',
                          'E107',
                          'E109',
                          'E110',
                          'E112',
                          'E113',
                          'E114',
                          'E115',
                          'E118' ],
               'Mesench' : [ 'E023',
                             'E025',
                             'E026',
                             'E049' ],
               'Muscle' : [ 'E089',
                            'E090',
                            'E100',
                            'E107',
                            'E108' ],
               'Myosat' : [ 'E052' ],
               'Neurosph' : [ 'E053',
                              'E054' ],
               'Other' : [ 'E066',
                           'E080',
                           'E086',
                           'E087',
                           'E088',
                           'E091',
                           'E096',
                           'E097',
                           'E098',
                           'E099',
                           'E113' ],
               'PrimaryCell' : [ 'E027',
                                 'E029',
                                 'E030',
                                 'E031',
                                 'E032',
                                 'E033',
                                 'E034',
                                 'E035',
                                 'E036',
                                 'E037',
                                 'E038',
                                 'E039',
                                 'E040',
                                 'E041',
                                 'E042',
                                 'E043',
                                 'E044',
                                 'E045',
                                 'E046',
                                 'E047',
                                 'E048',
                                 'E050',
                                 'E051',
                                 'E062',
                                 'E124' ],
               'PrimaryTissue' : [ 'E063',
                                   'E065',
                                   'E066',
                                   'E067',
                                   'E068',
                                   'E069',
                                   'E070',
                                   'E071',
                                   'E072',
                                   'E073',
                                   'E074',
                                   'E075',
                                   'E076',
                                   'E077',
                                   'E078',
                                   'E079',
                                   'E080',
                                   'E081',
                                   'E082',
                                   'E083',
                                   'E084',
                                   'E085',
                                   'E086',
                                   'E087',
                                   'E088',
                                   'E089',
                                   'E090',
                                   'E091',
                                   'E092',
                                   'E093',
                                   'E094',
                                   'E095',
                                   'E096',
                                   'E097',
                                   'E098',
                                   'E099',
                                   'E100',
                                   'E101',
                                   'E102',
                                   'E103',
                                   'E104',
                                   'E105',
                                   'E106',
                                   'E107',
                                   'E108',
                                   'E109',
                                   'E110',
                                   'E111',
                                   'E112',
                                   'E113' ],
               'Sm._Muscle' : [ 'E076',
                                'E078',
                                'E103',
                                'E111' ],
               'Thymus' : [ 'E093',
                            'E112' ],
               'ImmuneAndNeurosphCombinedIntoOneGroup' : [ 'E033',
                                                           'E034',
                                                           'E037',
                                                           'E038',
                                                           'E039',
                                                           'E040',
                                                           'E041',
                                                           'E042',
                                                           'E043',
                                                           'E044',
                                                           'E045',
                                                           'E047',
                                                           'E048',
                                                           'E062',
                                                           'E029',
                                                           'E030',
                                                           'E031',
                                                           'E032',
                                                           'E035',
                                                           'E036',
                                                           'E046',
                                                           'E050',
                                                           'E051',
                                                           'E053',
                                                           'E054' ],
               'all' : [ 'E001',
                         'E002',
                         'E003',
                         'E004',
                         'E005',
                         'E006',
                         'E007',
                         'E008',
                         'E009',
                         'E010',
                         'E011',
                         'E012',
                         'E013',
                         'E014',
                         'E015',
                         'E016',
                         'E017',
                         'E018',
                         'E019',
                         'E020',
                         'E021',
                         'E022',
                         'E023',
                         'E024',
                         'E025',
                         'E026',
                         'E027',
                         'E028',
                         'E029',
                         'E030',
                         'E031',
                         'E032',
                         'E033',
                         'E034',
                         'E035',
                         'E036',
                         'E037',
                         'E038',
                         'E039',
                         'E040',
                         'E041',
                         'E042',
                         'E043',
                         'E044',
                         'E045',
                         'E046',
                         'E047',
                         'E048',
                         'E049',
                         'E050',
                         'E051',
                         'E052',
                         'E053',
                         'E054',
                         'E055',
                         'E056',
                         'E057',
                         'E058',
                         'E059',
                         'E061',
                         'E062',
                         'E063',
                         'E065',
                         'E066',
                         'E067',
                         'E068',
                         'E069',
                         'E070',
                         'E071',
                         'E072',
                         'E073',
                         'E074',
                         'E075',
                         'E076',
                         'E077',
                         'E078',
                         'E079',
                         'E080',
                         'E081',
                         'E082',
                         'E083',
                         'E084',
                         'E085',
                         'E086',
                         'E087',
                         'E088',
                         'E089',
                         'E090',
                         'E091',
                         'E092',
                         'E093',
                         'E094',
                         'E095',
                         'E096',
                         'E097',
                         'E098',
                         'E099',
                         'E100',
                         'E101',
                         'E102',
                         'E103',
                         'E104',
                         'E105',
                         'E106',
                         'E107',
                         'E108',
                         'E109',
                         'E110',
                         'E111',
                         'E112',
                         'E113',
                         'E114',
                         'E115',
                         'E116',
                         'E117',
                         'E118',
                         'E119',
                         'E120',
                         'E121',
                         'E122',
                         'E123',
                         'E124',
                         'E125',
                         'E126',
                         'E127',
                         'E128',
                         'E129' ]
           }

mm_e_map = { 'e11.5_forebrain' : 'Embryonic day 11.5 forebrain',
          'e12.5_forebrain' : 'Embryonic day 12.5 forebrain',
          'e13.5_forebrain' : 'Embryonic day 13.5 forebrain',
          'e14.5_forebrain' : 'Embryonic day 14.5 forebrain',
          'e15.5_forebrain' : 'Embryonic day 15.5 forebrain',
          'e16.5_forebrain' : 'Embryonic day 16.5 forebrain',
          'P0_forebrain' : 'Day-of-birth forebrain',
          'e11.5_midbrain' : 'Embryonic day 11.5 midbrain',
          'e12.5_midbrain' : 'Embryonic day 12.5 midbrain',
          'e13.5_midbrain' : 'Embryonic day 13.5 midbrain',
          'e14.5_midbrain' : 'Embryonic day 14.5 midbrain',
          'e15.5_midbrain' : 'Embryonic day 15.5 midbrain',
          'e16.5_midbrain' : 'Embryonic day 16.5 midbrain',
          'P0_midbrain' : 'Day-of-birth midbrain',
          'e11.5_hindbrain' : 'Embryonic day 11.5 hindbrain',
          'e12.5_hindbrain' : 'Embryonic day 12.5 hindbrain',
          'e13.5_hindbrain' : 'Embryonic day 13.5 hindbrain',
          'e14.5_hindbrain' : 'Embryonic day 14.5 hindbrain',
          'e15.5_hindbrain' : 'Embryonic day 15.5 hindbrain',
          'e16.5_hindbrain' : 'Embryonic day 16.5 hindbrain',
          'P0_hindbrain' : 'Day-of-birth hindbrain',
          'e11.5_neural-tube' : 'Embryonic day 11.5 neural tube',
          'e12.5_neural-tube' : 'Embryonic day 12.5 neural tube',
          'e13.5_neural-tube' : 'Embryonic day 13.5 neural tube',
          'e14.5_neural-tube' : 'Embryonic day 14.5 neural tube',
          'e15.5_neural-tube' : 'Embryonic day 15.5 neural tube',
          'e16.5_neural-tube' : 'Embryonic day 16.5 neural tube',
          'e11.5_heart' : 'Embryonic day 11.5 heart',
          'e12.5_heart' : 'Embryonic day 12.5 heart',
          'e13.5_heart' : 'Embryonic day 13.5 heart',
          'e14.5_heart' : 'Embryonic day 14.5 heart',
          'e15.5_heart' : 'Embryonic day 15.5 heart',
          'e16.5_heart' : 'Embryonic day 16.5 heart',
          'P0_heart' : 'Day-of-birth heart',
          'e14.5_lung' : 'Embryonic day 14.5 lung',
          'e15.5_lung' : 'Embryonic day 15.5 lung',
          'e16.5_lung' : 'Embryonic day 16.5 lung',
          'P0_lung' : 'Day-of-birth lung',
          'e14.5_kidney' : 'Embryonic day 14.5 kidney',
          'e15.5_kidney' : 'Embryonic day 15.5 kidney',
          'e16.5_kidney' : 'Embryonic day 16.5 kidney',
          'P0_kidney' : 'Day-of-birth kidney',
          'e11.5_liver' : 'Embryonic day 11.5 liver',
          'e12.5_liver' : 'Embryonic day 12.5 liver',
          'e13.5_liver' : 'Embryonic day 13.5 liver',
          'e14.5_liver' : 'Embryonic day 14.5 liver',
          'e15.5_liver' : 'Embryonic day 15.5 liver',
          'e16.5_liver' : 'Embryonic day 16.5 liver',
          'P0_liver' : 'Day-of-birth liver',
          'e14.5_intestine' : 'Embryonic day 14.5 intestine',
          'e15.5_intestine' : 'Embryonic day 15.5 intestine',
          'e16.5_intestine' : 'Embryonic day 16.5 intestine',
          'P0_intestine' : 'Day-of-birth intestine',
          'e14.5_stomach' : 'Embryonic day 14.5 stomach',
          'e15.5_stomach' : 'Embryonic day 15.5 stomach',
          'e16.5_stomach' : 'Embryonic day 16.5 stomach',
          'P0_stomach' : 'Day-of-birth stomach',
          'e11.5_limb' : 'Embryonic day 11.5 limb',
          'e12.5_limb' : 'Embryonic day 12.5 limb',
          'e13.5_limb' : 'Embryonic day 13.5 limb',
          'e14.5_limb' : 'Embryonic day 14.5 limb',
          'e15.5_limb' : 'Embryonic day 15.5 limb',
          'e16.5_limb' : 'Embryonic day 16.5 limb',
          'e11.5_facial-prominence' : 'Embryonic day 11.5 facial prominence',
          'e12.5_facial-prominence' : 'Embryonic day 12.5 facial prominence',
          'e13.5_facial-prominence' : 'Embryonic day 13.5 facial prominence',
          'e14.5_facial-prominence' : 'Embryonic day 14.5 facial prominence',
          'e15.5_facial-prominence' : 'Embryonic day 15.5 facial prominence',
          'e16.5_facial-prominence' : 'Embryonic day 16.5 facial prominence' }

mm_e_prefixes = { 'all' : ['e11.5_forebrain',
                           'e12.5_forebrain',
                           'e13.5_forebrain',
                           'e14.5_forebrain',
                           'e15.5_forebrain',
                           'e16.5_forebrain',
                           'P0_forebrain',
                           'e11.5_midbrain',
                           'e12.5_midbrain',
                           'e13.5_midbrain',
                           'e14.5_midbrain',
                           'e15.5_midbrain',
                           'e16.5_midbrain',
                           'P0_midbrain',
                           'e11.5_hindbrain',
                           'e12.5_hindbrain',
                           'e13.5_hindbrain',
                           'e14.5_hindbrain',
                           'e15.5_hindbrain',
                           'e16.5_hindbrain',
                           'P0_hindbrain',
                           'e11.5_neural-tube',
                           'e12.5_neural-tube',
                           'e13.5_neural-tube',
                           'e14.5_neural-tube',
                           'e15.5_neural-tube',
                           'e11.5_heart',
                           'e12.5_heart',
                           'e13.5_heart',
                           'e14.5_heart',
                           'e15.5_heart',
                           'e16.5_heart',
                           'P0_heart',
                           'e14.5_lung',
                           'e15.5_lung',
                           'e16.5_lung',
                           'P0_lung',
                           'e14.5_kidney',
                           'e15.5_kidney',
                           'e16.5_kidney',
                           'P0_kidney',
                           'e11.5_liver',
                           'e12.5_liver',
                           'e13.5_liver',
                           'e14.5_liver',
                           'e15.5_liver',
                           'e16.5_liver',
                           'P0_liver',
                           'e14.5_intestine',
                           'e15.5_intestine',
                           'e16.5_intestine',
                           'P0_intestine',
                           'e14.5_stomach',
                           'e15.5_stomach',
                           'e16.5_stomach',
                           'P0_stomach',
                           'e11.5_limb',
                           'e12.5_limb',
                           'e13.5_limb',
                           'e14.5_limb',
                           'e15.5_limb',
                           'e11.5_facial-prominence',
                           'e12.5_facial-prominence',
                           'e13.5_facial-prominence',
                           'e14.5_facial-prominence',
                           'e15.5_facial-prominence'],
              'digestiveSystem' : ['e14.5_intestine',
                                   'e15.5_intestine',
                                   'e16.5_intestine',
                                   'P0_intestine',
                                   'e14.5_stomach',
                                   'e15.5_stomach',
                                   'e16.5_stomach',
                                   'P0_stomach'],
              'e11.5' : ['e11.5_forebrain',
                         'e11.5_midbrain',
                         'e11.5_hindbrain',
                         'e11.5_neural-tube',
                         'e11.5_heart',
                         'e11.5_liver',
                         'e11.5_limb',
                         'e11.5_facial-prominence'],
              'e12.5' : ['e12.5_forebrain',
                         'e12.5_midbrain',
                         'e12.5_hindbrain',
                         'e12.5_neural-tube',
                         'e12.5_heart',
                         'e12.5_liver',
                         'e12.5_limb',
                         'e12.5_facial-prominence'],
              'e13.5' : ['e13.5_forebrain',
                         'e13.5_midbrain',
                         'e13.5_hindbrain',
                         'e13.5_neural-tube',
                         'e13.5_heart',
                         'e13.5_liver',
                         'e13.5_limb',
                         'e13.5_facial-prominence'],
              'e14.5' : ['e14.5_forebrain',
                         'e14.5_midbrain',
                         'e14.5_hindbrain',
                         'e14.5_neural-tube',
                         'e14.5_heart',
                         'e14.5_lung',
                         'e14.5_kidney',
                         'e14.5_liver',
                         'e14.5_intestine',
                         'e14.5_stomach',
                         'e14.5_limb',
                         'e14.5_facial-prominence'],
              'e15.5' : ['e15.5_forebrain',
                         'e15.5_midbrain',
                         'e15.5_hindbrain',
                         'e15.5_neural-tube',
                         'e15.5_heart',
                         'e15.5_lung',
                         'e15.5_kidney',
                         'e15.5_liver',
                         'e15.5_intestine',
                         'e15.5_stomach',
                         'e15.5_limb',
                         'e15.5_facial-prominence'],
              'e16.5' : ['e16.5_forebrain',
                         'e16.5_midbrain',
                         'e16.5_hindbrain',
                         'e16.5_neural-tube',
                         'e16.5_heart',
                         'e16.5_lung',
                         'e16.5_kidney',
                         'e16.5_liver',
                         'e16.5_intestine',
                         'e16.5_stomach',
                         'e16.5_limb',
                         'e16.5_facial-prominence'],
              'facial-prominence' : ['e11.5_facial-prominence',
                                     'e12.5_facial-prominence',
                                     'e13.5_facial-prominence',
                                     'e14.5_facial-prominence',
                                     'e15.5_facial-prominence',
                                     'e16.5_facial-prominence'],
              'forebrain' : ['e11.5_forebrain',
                             'e12.5_forebrain',
                             'e13.5_forebrain',
                             'e14.5_forebrain',
                             'e15.5_forebrain',
                             'e16.5_forebrain',
                             'P0_forebrain'],
              'heart' : ['e11.5_heart',
                         'e12.5_heart',
                         'e13.5_heart',
                         'e14.5_heart',
                         'e15.5_heart',
                         'e16.5_heart',
                         'P0_heart'],
              'hindbrain' : ['e11.5_hindbrain',
                             'e12.5_hindbrain',
                             'e13.5_hindbrain',
                             'e14.5_hindbrain',
                             'e15.5_hindbrain',
                             'e16.5_hindbrain',
                             'P0_hindbrain'],
              'intestine' : ['e14.5_intestine',
                             'e15.5_intestine',
                             'e16.5_intestine',
                             'P0_intestine'],
              'kidney' : ['e14.5_kidney',
                          'e15.5_kidney',
                          'e16.5_kidney',
                          'P0_kidney'],
              'limb' : ['e11.5_limb',
                        'e12.5_limb',
                        'e13.5_limb',
                        'e14.5_limb',
                        'e15.5_limb',
                        'e16.5_limb'],
              'liver' : ['e11.5_liver',
                         'e12.5_liver',
                         'e13.5_liver',
                         'e14.5_liver',
                         'e15.5_liver',
                         'e16.5_liver',
                         'P0_liver'],
              'lung' : ['e14.5_lung',
                        'e15.5_lung',
                        'e16.5_lung',
                        'P0_lung'],
              'neural-tube' : ['e11.5_neural-tube',
                               'e12.5_neural-tube',
                               'e13.5_neural-tube',
                               'e14.5_neural-tube',
                               'e15.5_neural-tube',
                               'e16.5_neural-tube'],
              'P0' : ['P0_forebrain',
                      'P0_midbrain',
                      'P0_hindbrain',
                      'P0_heart',
                      'P0_lung',
                      'P0_kidney',
                      'P0_liver',
                      'P0_intestine',
                      'P0_stomach'],
              'stomach' : ['e14.5_stomach',
                           'e15.5_stomach',
                           'e16.5_stomach',
                           'P0_stomach']
           }

bounds = {
  "mm10" : {
    "chr1" : 195471971,
    "chr2" : 182113224,
    "chr3" : 160039680,
    "chr4" : 156508116,
    "chr5" : 151834684,
    "chr6" : 149736546,
    "chr7" : 145441459,
    "chr8" : 129401213,
    "chr9" : 124595110,
    "chr10" : 130694993,
    "chr11" : 122082543,
    "chr12" : 120129022,
    "chr13" : 120421639,
    "chr14" : 124902244,
    "chr15" : 104043685,
    "chr16" : 98207768,
    "chr17" : 94987271,
    "chr18" : 90702639,
    "chr19" : 61431566,
    "chrX" : 171031299,
    "chrY" : 91744698
  },
  "hg38" : {
    "chr1" : 248956422,
    "chr2" : 242193529,
    "chr3" : 198295559,
    "chr4" : 190214555,
    "chr5" : 181538259,
    "chr6" : 170805979,
    "chr7" : 159345973,
    "chr8" : 145138636,
    "chr9" : 138394717,
    "chr10" : 133797422,
    "chr11" : 135086622,
    "chr12" : 133275309,
    "chr13" : 114364328,
    "chr14" : 107043718,
    "chr15" : 101991189,
    "chr16" : 90338345,
    "chr17" : 83257441,
    "chr18" : 80373285,
    "chr19" : 58617616,
    "chr20" : 64444167,
    "chr21" : 46709983,
    "chr22" : 50818468,
    "chrX" : 156040895,
    "chrY" : 57227415
  },
  "hg19" : {
    "chr1" : 249250621,
    "chr2" : 243199373,
    "chr3" : 198022430,
    "chr4" : 191154276,
    "chr5" : 180915260,
    "chr6" : 171115067,
    "chr7" : 159138663,
    "chr8" : 146364022,
    "chr9" : 141213431,
    "chr10" : 135534747,
    "chr11" : 135006516,
    "chr12" : 133851895,
    "chr13" : 115169878,
    "chr14" : 107349540,
    "chr15" : 102531392,
    "chr16" : 90354753,
    "chr17" : 81195210,
    "chr18" : 78077248,
    "chr19" : 59128983,
    "chr20" : 63025520,
    "chr21" : 48129895,
    "chr22" : 51304566,
    "chrX" : 155270560,
    "chrY" : 59373566
  }
}

hg_cat_15 = { '1' : {'name':'Active TSS', 'color':'#ff0000'},
              '2' : {'name':'Flanking Active TSS', 'color':'#ff4500'},
              '3' : {'name':'Transcr at gene 5\' and 3\'', 'color':'#32cd32'},
              '4' : {'name':'Strong transcription', 'color':'#008000'},
              '5' : {'name':'Weak transcription', 'color':'#006400'},
              '6' : {'name':'Genic enhancers', 'color':'#c2e105'},
              '7' : {'name':'Enhancers', 'color':'#ffff00'}, 
              '8' : {'name':'ZNF genes & repeats', 'color':'#66cdaa'}, 
              '9' : {'name':'Heterochromatin', 'color':'#8a91d0'}, 
              '10' : {'name':'Bivalent/Poised TSS', 'color':'#cd5c5c'}, 
              '11' : {'name':'Flanking Bivalent TSS/Enh', 'color':'#e9967a'}, 
              '12' : {'name':'Bivalent Enhancer', 'color':'#bdb76b'}, 
              '13' : {'name':'Repressed PolyComb', 'color':'#808080'}, 
              '14' : {'name':'Weak Repressed PolyComb', 'color':'#c0c0c0'}, 
              '15' : {'name':'Quiescent/Low', 'color':'#ffffff'}
}

hg_cat_18 = { '1' : {'name':'Active TSS', 'color':'#FF0000'}, 
              '2' : {'name':'Flanking TSS', 'color':'#FF4500'}, 
              '3' : {'name':'Flanking TSS Upstream', 'color':'#FF4500'}, 
              '4' : {'name':'Flanking TSS Downstream', 'color':'#FF4500'}, 
              '5' : {'name':'Strong transcription', 'color':'#008000'}, 
              '6' : {'name':'Weak transcription', 'color':'#006400'}, 
              '7' : {'name':'Genic enhancer 1', 'color':'#C2E105'}, 
              '8' : {'name':'Genic enhancer 2', 'color':'#C2E105'}, 
              '9' : {'name':'Active Enhancer 1', 'color':'#FFC34D'}, 
              '10' : {'name':'Active Enhancer 2', 'color':'#FFC34D'}, 
              '11' : {'name':'Weak Enhancer', 'color':'#FFFF00'}, 
              '12' : {'name':'ZNF genes & repeats', 'color':'#66CDAA'}, 
              '13' : {'name':'Heterochromatin', 'color':'#8A91D0'}, 
              '14' : {'name':'Bivalent/Poised TSS', 'color':'#CD5C5C'}, 
              '15' : {'name':'Bivalent Enhancer', 'color':'#BDB76B'}, 
              '16' : {'name':'Repressed PolyComb', 'color':'#808080'}, 
              '17' : {'name':'Weak Repressed PolyComb', 'color':'#C0C0C0'}, 
              '18' : {'name':'Quiescent/Low', 'color':'#FFFFFF'} 
}

hg_cat_25 = { '1' : {'name':'Active TSS', 'color':'#ff0000'}, 
              '2' : {'name':'Promoter Upstream TSS', 'color':'#ff4500'}, 
              '3' : {'name':'Promoter Downstream TSS with DNase', 'color':'#ff4500'}, 
              '4' : {'name':'Promoter Downstream TSS', 'color':'#ff4500'}, 
              '5' : {'name':'Transcription 5\'', 'color':'#008000'}, 
              '6' : {'name':'Transcription', 'color':'#008000'}, 
              '7' : {'name':'Transcription 3\'', 'color':'#008000'}, 
              '8' : {'name':'Weak transcription', 'color':'#009600'}, 
              '9' : {'name':'Transcription Regulatory', 'color':'#c2e105'}, 
              '10' : {'name':'Transcription 5\' Enhancer', 'color':'#c2e105'}, 
              '11' : {'name':'Transcription 3\' Enhancer', 'color':'#c2e105'}, 
              '12' : {'name':'Transcription Weak Enhancer', 'color':'#c2e105'}, 
              '13' : {'name':'Active Enhancer 1', 'color':'#ffc34d'}, 
              '14' : {'name':'Active Enhancer 2', 'color':'#ffc34d'}, 
              '15' : {'name':'Active Enhancer Flank', 'color':'#ffc34d'}, 
              '16' : {'name':'Weak Enhancer 1', 'color':'#ffff00'}, 
              '17' : {'name':'Weak Enhancer 2', 'color':'#ffff00'}, 
              '18' : {'name':'Enhancer Acetylation Only', 'color':'#ffff00'}, 
              '19' : {'name':'DNase only', 'color':'#ffff66'}, 
              '20' : {'name':'ZNF genes & repeats', 'color':'#66cdaa'}, 
              '21' : {'name':'Heterochromatin', 'color':'#8a91d0'}, 
              '22' : {'name':'Poised Promoter', 'color':'#e6b8b7'}, 
              '23' : {'name':'Bivalent Promoter', 'color':'#7030a0'}, 
              '24' : {'name':'Repressed PolyComb', 'color':'#808080'}, 
              '25' : {'name':'Quiescent/Low', 'color':'#ffffff'}
}

mm_cat_15 = { '1' :  {'name':'Promoter - Active', 'color':'#0e6f37'}, 
              '2' :  {'name':'Promoter - Weak/Inactive', 'color':'#c7e4c0'}, 
              '3' :  {'name':'Promoter - Bivalent', 'color':'#cdcdcd'}, 
              '4' :  {'name':'Promoter - Flanking', 'color':'#41ac5e'}, 
              '5' :  {'name':'Enhancer - Strong, TSS-distal', 'color':'#f3eb1a'}, 
              '6' :  {'name':'Enhancer - Strong, TSS-proximal', 'color':'#f3eb1a'}, 
              '7' :  {'name':'Enhancer - Weak, TSS-distal', 'color':'#faf8c8'}, 
              '8' :  {'name':'Enhancer - Poised, TSS-distal', 'color':'#808080'}, 
              '9' :  {'name':'Enhancer - Poised, TSS-proximal', 'color':'#808080'}, 
              '10' : {'name':'Transcription - Strong', 'color':'#0454a3'}, 
              '11' : {'name':'Transcription - Permissive', 'color':'#deecf7'}, 
              '12' : {'name':'Transcription - Initiation', 'color':'#4290cf'}, 
              '13' : {'name':'Heterochromatin - Polycomb', 'color':'#f48c8f'}, 
              '14' : {'name':'Heterochromatin - H3K9me3', 'color':'#fde2e5'}, 
              '15' : {'name':'No signal', 'color':'#ffffff'}
}

#groups = ['adult_blood_reference',
#          'Brain_vs_Neurosph',
#          'cord_blood_sample_vs_cord_blood_reference',
#          'ESC_vs_iPSC',
#          'iPSC',
#          'Neurosph',
#          'Thymus',
#          'adult_blood_sample',
#          'Brain_vs_Other',
#          'Digestive',
#          'ES-deriv',
#          'Male',
#          'Other',
#          'adult_blood_sample_vs_adult_blood_reference',
#          'CellLine',
#          'ENCODE2012',
#          'Female',
#          'Male_vs_Female',
#          'PrimaryCell',
#          'CellLine_vs_PrimaryCell',
#          'Epithelial',
#          'Heart',
#          'Mesench',
#          'PrimaryTissue',
#          'Blood_T-cell',
#          'Non-T-cell_Roadmap',
#          'cord_blood_reference',
#          'ESC',
#          'HSC_B-cell',
#          'Muscle',
#          'PrimaryTissue_vs_PrimaryCell',
#          'Brain',
#          'cord_blood_sample',
#          'ESC_vs_ES-deriv',
#          'HSC_B-cell_vs_Blood_T-cell',
#          'Muscle_vs_Sm._Muscle',
#          'Sm._Muscle',
#          'ImmuneAndNeurosphCombinedIntoOneGroup',
#          'Blood_T-cell_vs_Non-T-cell_Roadmap',
#          'all',
#          'digestiveSystem',
#          'e11.5',
#          'e11.5_vs_P0',
#          'e12.5',
#          'e13.5',
#          'e14.5',
#          'e15.5',
#          'e16.5',
#          'facial-prominence',
#          'forebrain',
#          'forebrain_vs_hindbrain',
#          'heart',
#          'hindbrain',
#          'intestine',
#          'kidney',
#          'limb',
#          'liver',
#          'lung',
#          'neural-tube',
#          'P0',
#          'stomach']

groups = [
    'ESC',
    'ESC_vs_ES-deriv',
    'ESC_vs_iPSC',
    'ESC_vs_NonES-like',
    'NonES-like'
]

def mkdir_p(path):
    try:
        os.makedirs(path)
    except OSError as exc:  # Python >2.5
        if exc.errno == errno.EEXIST and os.path.isdir(path):
            pass
        else:
            raise

assemblies = ['hg19', 'hg38']
states = [15, 18, 25]
complexities = ['KL',
                'KLs',
                'KLss']

dest_dir = 'epilogos/vA'

@click.command()
def main():
    for assembly in assemblies:
        for state in states:
            for complexity in complexities:
                for group in groups:
                    # /home/areynolds/proj/wouter/110418/data/hg19/15/group_to_multivec/Thymus.KLss.gz.bed.map.reorder.multires.mv5
                    src_url = 'https://%s/~areynolds/proj/wouter/110418/data/esc_redo/exemplars/%s.%s.%s.%s.top100.txt' % (altius, assembly, state, group, complexity)
                    #print(src_url)
                    r = requests.get(src_url, timeout=15, stream=True, auth=HTTPBasicAuth(username, password))
                    if r.status_code != 200:
                        sys.stderr.write("Debug: Could not find [{}]\n".format(src_url))
                        raise SystemError()
                    elif r.status_code == 200:
                        exemplar_dest_dir = '%s/%s/%d/%s/%s/exemplar' % (dest_dir, assembly, state, group, complexity)
                        if not os.path.exists(exemplar_dest_dir):
                            mkdir_p(exemplar_dest_dir)
                        dest_fn = '%s/top100.txt' % (exemplar_dest_dir)
                        sys.stderr.write('copying | %s | to | %s | \n' % (src_url, dest_fn))
                        with open(dest_fn, 'wb') as f:
                            total_length = int(r.headers.get('content-length'))
                            for chunk in progress.bar(r.iter_content(chunk_size=(1024*512)), expected_size=(total_length/(1024*512)) + 1):
                                if chunk:
                                    f.write(chunk)
                                    f.flush()

if __name__ == '__main__':
    main()
